### PR TITLE
v 0.2.0 request

### PR DESCRIPTION
**Pull request by agentd00nut**
A branch from timeZynk that gives clearer instructions in the readme on how to use the client for new users while providing a counter and histogram test script.

In addition this restores the ability for the client to push to a pushgateway that timeZynk had removed.
It also provides an example config for the prometheus server to show how to pull from a pushgateway.

I would update the composer files but i don't know composer.

### CODE REVIEW

**Comment by Lazyshot** [comment]
I'll update the composer and gitignore so this can be merged.

**Comment by Dnile** [comment]
any news on this?

**Comment by LukasGrebe** [comment]
This would be great. Just found this Repo and now found a Readme to go with it.

**Comment by Lazyshot** [comment]
Sorry about the long delay, but this has been merged. I added back the composer stuff and a couple other things.

**Pull request merged**
